### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mahmad2504** [couling/WebDAV-Daemon#1]
webdavd.c:81:2: error: unknown type name ‘gnutls_pcert_st’
  gnutls_pcert_st * certs;
  ^

Is it due to some version mismatch?

**Comment by couling** [comment]
I've compiled the code myself against Ubuntu and Raspbian and both were fine.  It may be a dependency error. I'll close this issue now, if you do still have a problem then don't hesitate to re-open the issue.
