### ISSUE TITLE
Installation help please

### ISSUE THREAD

**Issue by Daxcor69** [couling/WebDAV-Daemon#29]
Sorry I am a linux ubuntu noob.  I was able to make the binary and config file.  However when I go to run it I get a internal server error and it wants to load that error file  from usr/share.  There isn't a make install so I am not sure where to put everything. Wondering if you can help out with a little more specifics

thanks
Brad

**Comment by sbluhm** [comment]
@Daxcor69 , can you please elaborate on what you have done (detailled steps, commands,...)  and on the issue that you are experiencing (error logs)?

An installation package is available on the [Releases page](https://github.com/couling/WebDAV-Daemon/releases/tag/v1.1).

On the contrary, if you "make" the binary yourself from the source code, all required files should be there or "make" would not finish completely.

**Comment by Daxcor69** [comment]
I am a total idiot. I missed the packages.  It works just fine.  I am having troubles mounting a windows mapped drive to the server but I don't think it is your application.  I am able to access the files via the browser just fine.  Sorry to bother you.

Brad
