### ISSUE TITLE
Self signed SSL certificate not accepted by Windows 10

### ISSUE THREAD

**Issue by FranckGoirand** [couling/WebDAV-Daemon#6]
I have create certificate in my server with this command line :
# openssl req -x509 -nodes -days 2730 -newkey rsa:2048 -keyout cert.key -out cert.crt -config req.cnf -sha256

I have put my certificate path in conf file
<listen>
                        <port>443</port>
                        <encryption>ssl</encryption>
                </listen>
                <rap-binary>build/rap</rap-binary>
                <static-response-dir>package-with/share</static-response-dir>
                <ssl-cert>
                        <certificate>/etc/ssl/private/cert.crt</certificate>
                        <key>/etc/ssl/private/cert.key</key>
                </ssl-cert>

But in Windows 10 when i put my URL : https://192.168.100.188.  It don't work with error "Impossible to open a session in the network".
Nothing logs server side.

It work nice in HTTP.

Thank you for your come back

**Comment by couling** [comment]
This sounds like windows is not accepting the certificate. Have you tried entering your URL (https://192.168.100.188) in a browser (IE or Edge)?

**Comment by couling** [comment]
As far as I know certificates do not work with IP addresses. You need to put a name (domain name or hostname) on the machine and make the certificate for that name.

You will also need to do something to get windows to accept the certificate if you are generating it for yourself.  For security Windows will only accept a certificate issued by a reputable CA.  If you don't want to pay for one or use Let's Encrypt then  you will need to register whatever certificate you generate for yourself in Windows to get it to be accepted.

**Comment by FranckGoirand** [comment]
Thank you Philip for your information. It works nice.
