### ISSUE TITLE
Add support for RHEL based systems

### ISSUE THREAD

**Issue by sbluhm** [couling/WebDAV-Daemon#8]
Add support for RHEL based systems (minimum RHEL8).

**Comment by couling** [comment]
Are you just looking for Redhat (RPM) packaging or something else?

**Comment by sbluhm** [comment]
#10

**Comment by sbluhm** [comment]
Yes, RPM packaging. Added the PR for you. Tested on CentOS 8.

**Comment by couling** [comment]
Merged
